spring:
  profiles:
    active: local

  datasource:
    url: jdbc:p6spy:h2:tcp://localhost:1521/querydsl
    username: sa
    password:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    show-sql: false
logging:
  level:
    org.hibernate.SQL: off
